GET http://localhost:8080/concerts
Accept: application/json

###
GET http://localhost:8080/concerts/1

###
DELETE http://localhost:8080/concerts/3


###
POST http://localhost:8080/concerts
Content-Type: application/json
Authorization: Basic admin goodpassword

{
    "concertName": "Coldplay Singapore 2023",
    "ticketQuantity": 8000
}

###
POST http://localhost:8080/concerts
Content-Type: application/json
Authorization: Basic admin goodpassword
# doesn't work because of short concert name

{
    "concertName": "Cold",
    "ticketQuantity": 8000
}
###
POST http://localhost:8080/concerts
Content-Type: application/json
Authorization: Basic admin goodpassword
# Validation failed - book title is null. wrong attribute!

{
    "eventName": "HOTplay Singapore 2023",
    "ticketQuantity": 8000
}
###
PUT http://localhost:8080/concerts/1
Content-Type: application/json
# Wrong username in Authorization
Authorization: Basic dt goodpassword

{
    "concertName": "Taylor Swift Singapore 2023",
    "ticketQuantity": 999000
}

###
# GET http://localhost:8080/concerts/1/


###
# POST http://localhost:8080/concerts/2
# Content-Type: application/json
# # User role
# Authorization: Basic gooduser:goodpassword

# {
#     "review": "Terrible book :)"
# }

###
# PUT http://localhost:8080/concerts/2
# Content-Type: application/json

# {
#     "review": "Should be bad!"
# }

###deleting concert works under admin privileges
DELETE http://localhost:8080/concerts/3
Content-Type: application/json
Authorization: Basic admin goodpassword

###unauthorised for non-admins
GET http://localhost:8080/users

###
POST http://localhost:8080/users
Content-Type: application/json

{
    "username": "donta",
    "password": "goodpassword",
    "authorities": "ROLE_ADMIN"
}

###
POST http://localhost:8080/users
Content-Type: application/json
Authorization: Basic admin goodpassword

{
    "username": "gooduser",
    "password": "goodpassword",
    "authorities": "ROLE_USER"
}

