### Ryan's methods
### Method found in ConcertServiceImpl.java
GET http://localhost:8080/sectorRowAvailability/1/634
Accept: application/json

### Method found in UserServiceImpl.java
GET http://localhost:8080/users/2/purchasedTickets
Content-Type: application/json
Authorization: Basic normaluser goodpassword

GET http://localhost:8080/concerts

###
GET http://localhost:8080/venues
Accept: application/json

###
GET http://localhost:8080/concerts/byId/1

###
GET http://localhost:8080/concerts/byName/taylor%20swift
# Should return 2 concerts containing the name "Taylor Swift"
# %20 is used to replace spaces in query
# Should be non-case sensitive

###
GET http://localhost:8080/concerts/byName/BST
# Should throw a 404 exception because there are no concerts whose name contains "BST"

###
DELETE http://localhost:8080/concerts/3


### outdated
POST http://localhost:8080/concerts
Content-Type: application/json
Authorization: Basic admin goodpassword

{
    "concertName": "Coldplay Singapore 2023",
    "ticketQuantity": 8000,
    "dateRange": "3 March, 2023",
    "startTime": "20:30",
    "concertVenue": "Singapore National Stadium",
    "photo": "src/main/resources/static/concert_posters/Coldplay_Concert_Poster.jpg"
}

### deleting concert works under admin privileges
DELETE http://localhost:8080/concerts/3
Content-Type: application/json
Authorization: Basic admin goodpassword

###
POST http://localhost:8080/concerts
Content-Type: application/json
Authorization: Basic admin goodpassword
# doesn't work because of short concert name

{
    "concertName": "Cold",
    "ticketQuantity": 8000
}
###
POST http://localhost:8080/concerts
Content-Type: application/json
Authorization: Basic admin goodpassword
# Validation failed - concertName is null. wrong attribute name!

{
    "concertName": "HOTplay Singapore 2023",
    "ticketQuantity": 8000,
    "dateRange": "3 March, 2023",
    "startTime": "20:30",
    "concertVenue": "Singapore National Stadium",
    "photo": "src/main/resources/static/concert_posters/Coldplay_Concert_Poster.jpg"
}
###
PUT http://localhost:8080/concerts/1
Content-Type: application/json
# Wrong username in Authorization
Authorization: Basic dt goodpassword

{
    "concertName": "HOTplay Singapore 2023",
    "ticketQuantity": 8000,
    "dateRange": "3 March, 2023",
    "startTime": "20:30",
    "concertVenue": "Singapore National Stadium",
    "photo": "src/main/resources/static/concert_posters/Coldplay_Concert_Poster.jpg"
}

###unauthorised for non-admins
GET http://localhost:8080/users
Authorization: Basic admin goodpassword

###unauthorised for non-admins
GET http://localhost:8080/users/admin
Authorization: Basic admin goodpassword

Content-Type: application/json
Authorization: Basic admin goodpassword

###
GET http://localhost:8080/currentDetail
Authorization: Basic normaluser goodpassword


###only admins can create admin
POST http://localhost:8080/adminUsers
Authorization: Basic admin goodpassword
Content-Type: application/json

{
    "username": "donta",
    "password": "goodpassword",
    "authorities": "ROLE_ADMIN",
    "emailAddress": "hello@gmail.com",
    "birthday": "123"
}

###
POST http://localhost:8080/save
Content-Type: application/json
Authorization: basic admin goodpassword

{
    "username": "gooduser",
    "password": "goodpassword",
    "birthday": "2001-04-04",
    "authorities": "ROLE_USER",
    "emailAddress": "hellohi@gmail.com",
    "address": "sdfdsf"
}

###
POST http://localhost:8080/addUser
Content-Type: application/json
Authorization: basic admin goodpassword
# To test with delete user function
# IDs are not repeated; deletion does not affect increment

{
    "username": "gooduser",
    "password": "goodpassword",
    "birthday": "2001-04-04",
    "authorities": "ROLE_USER",
    "emailAddress": "hellohi@gmail.com",
    "address": "sdfdsf"
}

###
DELETE http://localhost:8080/users/3
Content-Type: application/json
Authorization: basic admin goodpassword
# UserNotFoundException works

###
POST http://localhost:8080/tickets
Content-Type: application/json
Authorization: basic admin goodpassword

{
    "ticketType": "VIP",
    "seatDetails": "V4",
    "ticketStatus": "A"
}

###
GET http://localhost:8080/tickets/1/status
GET http://localhost:8080/tickets
Authorization: Basic admin goodpassword
Content-Type: application/json

###
GET http://localhost:8080/tickets/12
Authorization: Basic admin goodpassword
Content-Type: application/json

###
POST http://localhost:8080/tickets
Authorization: Basic admin goodpassword
Content-Type: application/json

{
    "ticketType": "NORMAL",
    "seatNumber": 13
}
