GET http://localhost:8080/concerts
Accept: application/json

###
GET http://localhost:8080/concerts/1

###
DELETE http://localhost:8080/concerts/abc


###
POST http://localhost:8080/concerts
Content-Type: application/json
Authorization: Basic admin goodpassword

{
    "title": "The Great Ideas"
}
###
POST http://localhost:8080/concerts
Content-Type: application/json
Authorization: Basic admin goodpassword
# Validation failed - book title is null

{
    "concertName": "Coldplay Singapore 2023",
    "ticketQuantity": 8000
}
###
PUT http://localhost:8080/concerts/1
Content-Type: application/json
# Wrong username
Authorization: Basic dt goodpassword

{
    "concertName": "Taylor Swift Singapore 2023",
    "ticketQuantity": 999000
}

###
GET http://localhost:8080/concerts/1/


###
# POST http://localhost:8080/concerts/2
# Content-Type: application/json
# # User role
# Authorization: Basic gooduser:goodpassword

# {
#     "review": "Terrible book :)"
# }

###
# PUT http://localhost:8080/concerts/2
# Content-Type: application/json

# {
#     "review": "Should be bad!"
# }

###
DELETE http://localhost:8080/concerts/3

###
GET http://localhost:8080/users

###
POST http://localhost:8080/users
Content-Type: application/json

{
    "username": "donta",
    "password": "goodpassword",
    "authorities": "ROLE_ADMIN"
}

###
POST http://localhost:8080/users
Content-Type: application/json
Authorization: Basic admin goodpassword

{
    "username": "gooduser",
    "password": "goodpassword",
    "authorities": "ROLE_USER"
}

